name: Build docs for v5.x

on:
  push:
    branches: [ feature/v5.2 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v5.1, v5.2]

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_DOC_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - uses: actions/checkout@v2

      - name: Clone zedgraph.github.io repo
        run: |
         git clone git@github.com:ZedGraph/zedgraph.github.io.git site

      - name: Clone ZedGraph/ZedGraph repo
        run: |
         git clone --branch maintenance/${{ matrix.version }} git@github.com:ZedGraph/ZedGraph.git sources

      - name: Build Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
         args: ${{ matrix.version }}/docfx.json

      - name: Publish to github pages
        run: |
          cd site
          rm -rf ${{ matrix.version }}
          cp -a ../${{ matrix.version }}/_site/. ./${{ matrix.version }}/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --reset-author --amend -m "Deploy v5.x docs"
          git push --force origin
